# Generated by Django 2.0.5 on 2019-04-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190327_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apppreferrence',
            name='username',
        ),
        migrations.RemoveField(
            model_name='pollanswer',
            name='post',
        ),
        migrations.RemoveField(
            model_name='pollquestions',
            name='post',
        ),
        migrations.DeleteModel(
            name='AppPreferrence',
        ),
        migrations.DeleteModel(
            name='PollAnswer',
        ),
        migrations.DeleteModel(
            name='PollQuestions',
        ),
    ]
