# Generated by Django 2.0.13 on 2019-03-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180613_1952'),
        ('blog', '0003_auto_20181011_2251'),
    ]

    operations = [
    ]
