# Generated by Django 2.0.5 on 2018-06-19 18:43

import blog.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180613_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_name',
            field=enumfields.fields.EnumField(default='A', enum=blog.models.Category, max_length=1),
        ),
    ]
