# Generated by Django 2.0.5 on 2018-10-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rec_value',
            field=models.IntegerField(default=1),
        ),
    ]
