# Generated by Django 2.0.5 on 2018-06-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='replies',
            new_name='short_desc',
        ),
    ]
