# Generated by Django 2.0.5 on 2018-06-26 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_apppreferrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppreferrence',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
