# Generated by Django 2.0.5 on 2018-12-13 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userprofile',
        ),
    ]
