# Generated by Django 2.0.5 on 2018-06-27 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20180626_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPreferrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=40)),
                ('vote_value', models.IntegerField(default=0)),
                ('vote_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('postpk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='postpreferrence',
            unique_together={('username', 'postpk', 'ip_address')},
        ),
    ]
