# Generated by Django 2.0.5 on 2018-07-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180711_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_name',
            field=models.CharField(max_length=200),
        ),
    ]
