# Generated by Django 2.0.5 on 2018-07-10 23:49

import blog.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180711_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_name',
            field=enumfields.fields.EnumField(default='Struggling with harassment?', enum=blog.models.Category, max_length=30),
        ),
    ]
