# Generated by Django 2.0.5 on 2018-12-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_pollanswer_pollquestions_pollstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollanswer',
            old_name='choice1val',
            new_name='choiceval',
        ),
        migrations.RemoveField(
            model_name='pollanswer',
            name='choice2val',
        ),
        migrations.RemoveField(
            model_name='pollanswer',
            name='choice3val',
        ),
        migrations.RemoveField(
            model_name='pollanswer',
            name='choice4val',
        ),
    ]
