# Generated by Django 2.0.5 on 2018-12-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181214_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestions',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
