# Generated by Django 2.0.5 on 2019-03-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='ip',
            field=models.CharField(db_index=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='hit',
            name='session',
            field=models.CharField(db_index=True, editable=False, max_length=40),
        ),
    ]
