# Generated by Django 2.0.5 on 2018-12-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0002_index_ip_and_session'),
        ('hitcount', '0002_auto_20181213_0012'),
    ]

    operations = [
    ]
